// Bu dosyayı bir kere çalıştır, hikayeleri Supabase'e yükler
import { sb } from './supabase'

const STORIES = [
  // ── MASAL - YOUNG ──
  { genre:'masal', age_group:'young', title:'Uyuyan Ormanın Sırrı',
    paragraphs:['Küçük Ela ormanda yürürken parlak bir ışık gördü. Işık bir ağacın arkasından geliyordu.','Ağacın arkasında küçük bir peri duruyordu. Peri elinde sihirli bir değnek tutuyordu.','Peri Ela\'ya dedi ki: Orman uyuyor, onu uyandırmak için şarkı söylemelisin!','Ela derin bir nefes aldı ve en güzel şarkısını söyledi. Çiçekler açtı, kuşlar uçtu!','Orman uyandı ve tüm hayvanlar Ela\'ya teşekkür etti. O gün en mutlu gün oldu.'],
    image_prompts:['small girl glowing light magical forest cartoon style','tiny fairy magical wand sparkling cute illustration','fairy and girl talking in enchanted forest colorful','girl singing flowers blooming birds flying vibrant cartoon','forest animals celebrating happy girl children book illustration'],
    moral:'Cesur ol ve kalbinden gelen sesi dinle.' },
  { genre:'masal', age_group:'young', title:'Üç Renkli Ejderha',
    paragraphs:['Küçük ejderha Alev üç farklı renkte ateş püskürtebiliyordu: kırmızı, mavi ve sarı.','Köydeki çocuklar ondan korkuyordu ama Alev çok iyi kalpli bir ejderhaydı.','Bir gün köyün fırını bozuldu. Alev kırmızı ateşiyle ekmeği pişirdi!','Sonra nehir dondu. Alev mavi ateşiyle buzu eritti ve herkes su içebildi.','Artık köylüler Alev\'i seviyordu. Farklı olmak bazen çok işe yarıyordu!'],
    image_prompts:['small colorful dragon three colors cute cartoon','dragon and scared children in village friendly illustration','dragon baking bread with red fire children book','dragon melting ice with blue fire colorful cartoon','happy villagers celebrating friendly dragon vibrant illustration'],
    moral:'Farklılıkların seni özel kılar.' },
  { genre:'masal', age_group:'young', title:'Kayıp Yıldız',
    paragraphs:['Gökyüzünden bir yıldız düştü ve küçük Mira\'nın bahçesine indi.','Yıldız ağlıyordu çünkü ailesini kaybetmişti ve gökyüzüne dönemiyordu.','Mira yıldıza sarıldı ve onu teselli etti. Birlikte buluruz dedi.','İkisi birlikte en yüksek tepeye tırmandılar. Oradan gökyüzü çok yakındı.','Yıldız uçtu ve gökyüzüne döndü. Her gece Mira\'ya en parlak ışığını gönderdi.'],
    image_prompts:['small star fallen in garden glowing cute cartoon','sad little star crying girl comforting illustration','girl and star climbing hill together colorful','girl and star on top of hill moonlight children book','bright star shining girl watching from window magical illustration'],
    moral:'Bir arkadaşa yardım etmek en güzel şeydir.' },
  { genre:'masal', age_group:'young', title:'Büyülü Tohumlar',
    paragraphs:['Dede Ahmet torununa üç sihirli tohum verdi. Dikkatli ek dedi.','Ali ilk tohumu güneşli yere ekti. Sabah devasa bir çiçek açmıştı!','İkinci tohumu suya attı. Oradan balıkları konuşturan bir bitki çıktı.','Üçüncü tohumu kalbinin üstüne tuttu ve rüzgara bıraktı.','Tohum tüm köye uçtu ve her yere çiçekler saçtı. Köy rengarenk oldu!'],
    image_prompts:['old grandfather giving seeds to grandson warm illustration','boy planting seed giant flower blooming colorful cartoon','magical plant in water talking fish children book','boy holding seed wind blowing magical scene','colorful flowers blooming all over village vibrant cartoon'],
    moral:'Sevgiyle yapılan her şey güzel meyve verir.' },
  { genre:'masal', age_group:'young', title:'Küçük Dev Kaplumbağa',
    paragraphs:['Minik kaplumbağa Yavaş arkadaşları gibi hızlı koşamıyordu.','Tavşan her gün onunla alay ediyordu ama Yavaş üzülmüyordu.','Bir gün ormanda büyük bir yangın çıktı. Herkes panikle koştu.','Yavaş sakin sakin yürüdü ve kayıp yavru tilkiyi buldu. Onu taşıdı!','Artık hiç kimse Yavaş ile alay etmiyordu. O gerçek bir kahramandı.'],
    image_prompts:['small slow turtle with friends in forest cute cartoon','rabbit teasing turtle children book illustration','forest fire animals running scared colorful illustration','turtle carrying baby fox heroic illustration','animals celebrating turtle as hero vibrant cartoon'],
    moral:'Hız değil cesaret ve sabır seni kahraman yapar.' },

  // ── MASAL - MIDDLE ──
  { genre:'masal', age_group:'middle', title:'Kayıp Krallığın Anahtarı',
    paragraphs:['Genç savaşçı Kaya antik bir haritada gizemli bir krallığın izlerini buldu.','Harita ona üç görev veriyordu: cesaret, zeka ve sevgi gerektiren görevler.','İlk görevde korkutucu bir ejderhanın karşısına çıktı ama onu dinleyerek sakinleştirdi.','İkinci görevde karmaşık bir labirenti çözdü; duvarların üzerine tırmanarak çıkış yolunu buldu.','Son görevde ise krallığın anahtarını bulmak için arkadaşlığını seçti. Kaya kazandı.'],
    image_prompts:['young warrior ancient map mystical kingdom fantasy illustration','hero facing dragon in cave glowing adventure art','warrior navigating labyrinth climbing walls dynamic illustration','warrior finding golden key sacred chamber epic fantasy','warrior and friends celebrating kingdom restored colorful adventure'],
    moral:'Gerçek güç cesaret, zeka ve sevginin birleşimindedir.' },
  { genre:'masal', age_group:'middle', title:'Sis Dağının Gizemli Bekçisi',
    paragraphs:['Her sabah sis dağından tuhaf sesler geliyordu ama kimse yukarı çıkmaya cesaret edemiyordu.','Meraklı Defne tek başına dağa tırmanmaya karar verdi.','Zirvede dev bir kaplumbağa buldu; yüzlerce yıldır orada yaşıyordu.','Kaplumbağa ona dünyanın sırlarını anlattı; her sesin bir anlamı olduğunu öğretti.','Defne köye döndüğünde artık rüzgarın dilini yağmurun sesini anlayabiliyordu.'],
    image_prompts:['mysterious foggy mountain village below fantasy art','brave girl climbing misty mountain alone adventure illustration','giant ancient tortoise mountain peak wisdom fantasy','girl listening to ancient tortoise stories magical illustration','girl returned to village listening to wind rain mystical art'],
    moral:'Merak bilgeliğin kapısını açar.' },
  { genre:'masal', age_group:'middle', title:'Gümüş Okun Efsanesi',
    paragraphs:['Ormanda kaybolmuş bir ok bulundu; onu tutan kişi dilediği şeyi görebiliyordu.','Üç çocuk oku bulmak için yolculuğa çıktı: Aslan güçlü, Deniz zeki, Pınar ise nazikti.','Aslan gücüyle engelleri aşıyordu; Deniz bulmacaları çözüyordu; Pınar ise herkesi bir arada tutuyordu.','Gümüş ok bir bulutun içinde saklıydı. Sadece üçü birlikte dokunabildi.','Ok onlara şunu gösterdi: En büyük güç arkadaşlıkta saklıdır.'],
    image_prompts:['three young adventurers beginning quest forest colorful fantasy','strong clever kind children working together illustration','team overcoming obstacles forest quest adventure art','silver arrow glowing in cloud three children magical fantasy','three friends holding silver arrow together glowing triumph illustration'],
    moral:'Tek başına güçlüsün ama birlikte efsanesin.' },
  { genre:'masal', age_group:'middle', title:'Unutulmuş Şehrin Şarkısı',
    paragraphs:['Yeraltında bir şehir varmış; halk müziklerini unutunca her şeyleri donup kalmış.','Genç müzisyen Arda bir gün bu şehre indi ve dondurulmuş insanları gördü.','Her birinin kalbinde unutulmuş bir melodi vardı; Arda onları dinlemeye başladı.','Parmaklarını teline değdirdi ve hepsini tek tek çalmaya başladı. Buzlar eridi!','Şehir halkı uyandı. Artık her gece şarkıları gökyüzüne yükseliyordu.'],
    image_prompts:['underground frozen city in ice fantasy art','young musician entering ice city lute magical illustration','frozen people with glowing hearts melodies mystical art','musician playing lute ice melting magic fantasy illustration','underground city awakened people celebrating music vibrant fantasy'],
    moral:'Müzik ve sanat ruhu donmaktan korur.' },
  { genre:'masal', age_group:'middle', title:'Deniz Canavarının Hediyesi',
    paragraphs:['Balıkçı köyü deniz canavarından korkuyor ama canavar yalnızca yardım istiyordu.','Genç Ada canavarın aslında hasta olduğunu fark etti; ağında büyük bir kanca vardı.','Kimse ona yardım etmezken Ada teknesini sürüp canavarın yanına gitti.','Saatler süren bir uğraşla kancayı çıkardı. Canavar yavaşça derinlere döndü.','O günden sonra fırtına geldiğinde canavar köyü korudu.'],
    image_prompts:['fishing village scared of sea monster stormy illustration','young girl noticing monster in pain hook compassionate art','brave girl in small boat approaching monster dramatic sea illustration','girl removing hook from sea monster careful touching fantasy art','sea monster protecting village from storm grateful epic illustration'],
    moral:'Cesaret korkuyu aşar, sevgi düşmanı dosta çevirir.' },

  // ── MASAL - TEEN ──
  { genre:'masal', age_group:'teen', title:'Zamanın Bekçisi',
    paragraphs:['Layla antika bir saatin içinde zamanın durduğu anı keşfetti. Her dişli bir anıyı saklıyordu.','İçine girdiğinde geçmişin koridorlarında yürüdü; büyükannesinin gençliğini gördü.','Zamanı değiştirmeye çalıştığında evren onu durdurdu; bazı anlar değiştirilemezdi.','Ama anlayışla yaklaşırsa geçmişten öğrenip geleceği şekillendirebilirdi.','Saati kapattığında içi hem hüzün hem umutla doluydu. Artık zamanı anlıyordu.'],
    image_prompts:['girl discovering antique clock glowing gears mystical art','girl walking through corridors of time memories surreal fantasy','girl watching grandmother young past timeline emotional illustration','girl realizing cannot change past accepting profound art','girl closing clock understanding time wisdom meaningful illustration'],
    moral:'Geçmiş değişmez ama ondan ne öğrendiğin her şeyi değiştirir.' },
  { genre:'masal', age_group:'teen', title:'Gölgelerin Ötesinde',
    paragraphs:['Herkesin bir gölgesi vardı ama Emre\'nin gölgesi hiç durmadan hareket ediyordu.','Gölgesi ona hayatın görmek istemediği gerçeklerini gösteriyordu.','Önce kaçmaya çalıştı; sonra onu susturmaya; sonunda onu dinlemeye karar verdi.','Gölgesinin her hareketi bir iç sesin mesajıydı: dürüst ol, cesur ol, gerçek ol.','Gölgesini kabul ettiğinde onu kontrol etmeyi öğrendi. Artık korkusu gücüne dönüşmüştü.'],
    image_prompts:['boy with moving restless shadow city atmospheric art','shadow showing boy uncomfortable truths mirror psychological illustration','boy chasing his own shadow running dynamic art','boy sitting listening to his shadow night introspective illustration','boy and shadow walking together in harmony powerful symbolic art'],
    moral:'Kendi iç sesinle yüzleşmek en büyük cesarettir.' },
  { genre:'masal', age_group:'teen', title:'Son Kütüphaneci',
    paragraphs:['2150 yılında kitaplar yasaklanmıştı; son kütüphaneci Naz yeraltında binlerce kitabı saklıyordu.','Hikayeler insanlığın hafızasıydı; onsuz kimse kim olduğunu bilemezdi.','Yetkililer peşindeydi ama Naz her gece gizlice kitapları çocuklara okuyordu.','Kelimeler ağızdan ağıza yayıldı; şiirler, masallar, tarih... Bunlar silinemezdi.','Sonunda halk uyanarak yasayı değiştirdi. Naz özgür kütüphaneci olarak anılacaktı.'],
    image_prompts:['underground library futuristic dystopia glowing books cyberpunk fantasy','last librarian protecting books darkness future dramatic illustration','librarian secretly reading stories to children underground emotional art','words spreading mouth to mouth glowing city symbolic illustration','people awakening reclaiming library future triumphant art'],
    moral:'Hikayeler susturulamaz; özgürlük kelimelerle başlar.' },
  { genre:'masal', age_group:'teen', title:'Boş Taht',
    paragraphs:['Kraliçe ölmeden önce tahtı en layık olana bırakmıştı ama kimin layık olduğunu söylememişti.','Üç aday vardı: güçlü prens, zeki prenses ve halktan gelen genç çoban.','Prens orduyu yönetmeye çalıştı; prenses yasaları değiştirdi; çoban ise halkı dinledi.','Yıllar geçti; halk çobanı seçmek istedi çünkü o onları görmüştü.','Çoban tahtı kabul etti ama krallığı halkla birlikte yönetti. Liderlik hizmet etmektir.'],
    image_prompts:['empty throne golden palace waiting epic fantasy art','three candidates prince princess shepherd waiting dramatic illustration','shepherd listening carefully to village people touching art','people gathering pointing at shepherd choice powerful illustration','shepherd on throne people together governing meaningful fantasy'],
    moral:'Gerçek lider güç değil hizmet için tahtı kabul eder.' },
  { genre:'masal', age_group:'teen', title:'Haritasız Yolculuk',
    paragraphs:['Elif 17 yaşında elinde hiçbir harita olmadan yabancı bir ülkeye geldi.','Dili bilmiyordu, yolu bilmiyordu, ama merakı ve gülümsemesi vardı.','Her yabancı bir kapı açtı; her hata yeni bir yol gösterdi.','Kaybolmak onu korkutmadı; aksine en güzel keşifleri böyle yaptı.','Eve döndüğünde anladı: en iyi harita içindedir ve her adımda çizilir.'],
    image_prompts:['young girl arriving foreign country alone suitcase journey illustration','girl communicating through gestures smiles strangers warm art','girl discovering beautiful place while lost adventure illustration','girl exploring unknown streets curiosity joy vibrant art','girl returning home confident transformed meaningful illustration'],
    moral:'Kaybolmaktan korkmak bulmanın önüne geçer.' },

  // ── KORKU - YOUNG ──
  { genre:'korku', age_group:'young', title:'Karanlık Odanın Arkadaşı',
    paragraphs:['Her gece Tuna karanlıktan korkardı. Dolabının ardında bir şey olduğunu düşünürdü.','Bir gece cesaret edip dolabı açtı. İçinde küçük tüylü bir yaratık vardı!','Yaratık da aynı şekilde korkmuş titriyordu. Ben de senden korkuyorum dedi.','İkisi birlikte güldüler. Yaratığın adı Puf\'tu ve karanlıkta ışık saçıyordu.','O günden sonra Tuna yalnız uyumadı. Puf her gece odasını aydınlattı.'],
    image_prompts:['child scared of dark bedroom shadows gentle cartoon','child opening closet finding small fluffy creature cute illustration','child and friendly creature laughing together warm cartoon','small glowing friendly monster bedroom cozy illustration','child sleeping peacefully with glowing friend nearby sweet cartoon'],
    moral:'Korkular bazen beklediğin arkadaşı saklar.' },
  { genre:'korku', age_group:'young', title:'Cadı Ormanındaki Ev',
    paragraphs:['Köyün çocukları cadı ormanına girmezdi ama Ali merak ediyordu.','Ormana girince kocaman bir ev gördü. Kapı yavaşça açıldı.','İçeride yaşlı bir kadın vardı. Hoş geldin, seni bekliyordum dedi.','Kadın aslında büyücüydü ama kötü değil, yalnızca yanlış anlaşılıyordu.','Ali o günden sonra her hafta ona ziyarete gitti ve birlikte sihir öğrendi.'],
    image_prompts:['forbidden dark forest village children watching cartoon illustration','boy entering mysterious house forest slightly spooky cartoon','old woman welcoming boy inside magical house warm illustration','kind witch and boy in magical kitchen colorful cartoon','boy and witch practicing friendly magic together joyful illustration'],
    moral:'Görünüşe göre yargılama; içini öğren.' },
  { genre:'korku', age_group:'young', title:'Gecenin Sesi',
    paragraphs:['Her gece saat 12\'de evin altından tuhaf sesler geliyordu.','Küçük Selin korkudan yorganını başına çekiyordu ama sesler durmuyor du.','Bir gece babasıyla birlikte bodruma indi. Sesler giderek yaklaşıyordu.','Bodrumdaki eski sandalye rüzgarda sallanıyor ve gıcırdıyordu!','Selin güldü ve sandalyeyi sevdi. Artık o ses onu korkutmuyor, uyutuyordu.'],
    image_prompts:['dark house at night with strange sounds gentle spooky cartoon','small girl hiding under covers scared cute illustration','girl and father going downstairs with flashlight warm cartoon','creaky old rocking chair in basement moonlight illustration','girl laughing at rocking chair relieved sweet cartoon'],
    moral:'Çoğu zaman korktuğumuz şey aslında çok masumdur.' },
  { genre:'korku', age_group:'young', title:'Hayalet mi Arkadaş mı',
    paragraphs:['Yeni eve taşındıklarında Zeynep aynada başka bir kızın yansımasını gördü.','Kız da Zeynep gibi saçlarını örgü yapıyordu ve gülümsüyordu.','Zeynep korktu ama kız onu taklit etmiyordu, selamlaşmaya çalışıyordu.','Yavaş yavaş iletişim kurdular; kız eskiden o evde yaşamış, artık görünmez bir arkadaştı.','Her gece aynada birlikte oynuyorlardı. Hayaletler de yalnız kalmak istemez.'],
    image_prompts:['girl seeing reflection other girl in mirror gentle spooky cartoon','two girls mirroring each other through mirror cute illustration','ghost girl waving hello friendly in mirror warm cartoon','two girls playing games through mirror colorful illustration','girl and ghost friend in mirror happy sweet cartoon'],
    moral:'Yalnızlık hem görünür hem görünmez herkesi etkiler.' },
  { genre:'korku', age_group:'young', title:'Balkondaki Ayak Sesleri',
    paragraphs:['Her gece balkonda ayak sesleri duyuluyordu. Hiç kimse yoktu ama sesler geliyordu.','Küçük Ömer pencereden baktı. Ayak izleri vardı ama sahipsiz gibi görünüyordu.','Bir gece dışarı çıktı. Büyük bir kedi balkondan balkona atlıyordu!','Kedi her gece gezintisine çıkıyordu. Çok şişman ve meraklı bir kediydi.','Ömer kediye salam koydu. Kedi artık her gece onu ziyarete geldi.'],
    image_prompts:['balcony night mysterious footsteps sounds gentle spooky cartoon','boy looking out window at balcony footprints curious cartoon','chubby cat jumping between balconies night funny illustration','boy discovering fat curious cat on balcony sweet cartoon','boy and cat friends on balcony night warm cozy illustration'],
    moral:'Gizemler çözüldüğünde arkadaşlık başlar.' },

  // ── KORKU - MIDDLE ──
  { genre:'korku', age_group:'middle', title:'Sisli Göldeki Tekne',
    paragraphs:['Göl her sabah sisli olurdu ve kimse içine girmezdi. Ta ki Kaan\'ın topu düşene kadar.','Topu almak için kıyıya yakın durdu ama sis içinde bir tekne belirdi.','Teknede oturan yaşlı adam onu adıyla çağırdı. Ama nasıl biliyordu?','Adam bu gölün bekçisiydi; her çocuğun adını biliyordu çünkü onların rüyalarını izliyordu.','Kaan\'a bir şey söyledi: Sisten korkan asla diğer yakayı göremez. Sonra kayboldu.'],
    image_prompts:['misty lake early morning foggy atmospheric illustration','boy reaching for ball near misty lake edge adventure art','old rowboat emerging from thick fog mysterious spooky illustration','old man in boat knowing child mysterious eerie art','boy standing at misty lake edge contemplating meaningful illustration'],
    moral:'Belirsizliğe rağmen ilerlemek cesaretin ta kendisidir.' },
  { genre:'korku', age_group:'middle', title:'Köhnemiş Evin Saatleri',
    paragraphs:['Terk edilmiş evde tüm saatler aynı saati gösteriyordu: gece 3:07.','Meraklı ikizler Bora ve Berk içeri girdi. Her odada farklı bir hikaye saklıydı.','O saatte burada bir şey olmuştu; duvarlar fısıldıyordu.','Gizli bir odada eski bir günlük buldular. Ev sahibinin son notuydu.','Adam hiçbir zaman geri dönememiş ve saat onun için durmuştu. Onlar saatin ibrelerini hareket ettirdi.'],
    image_prompts:['abandoned house all clocks showing same time atmospheric art','twin boys exploring abandoned house flashlights adventure illustration','whispering walls old house mysterious shadows spooky art','twins finding hidden diary dusty room discovery illustration','twins moving clock hands time flows again meaningful art'],
    moral:'Bazı hikayeler seni bulana kadar bekler.' },
  { genre:'korku', age_group:'middle', title:'Aynada Yabancı',
    paragraphs:['Elif yeni eve taşındıktan sonra aynada bazen kendisi yerine başka biri görünüyordu.','Başta panikledi ama yansıma ona zarar vermiyordu; sadece izliyordu.','Araştırdı: eski ev sahibi bir ressam, her gün aynaya bakarak çalışırmış.','Ressam resme öyle dalmış ki ruhu aynada kalmış. Şimdi bir izleyici olmuştu.','Elif her gece ressama kendi çizimlerini gösterdi. Yansıma her seferinde gülümsedi.'],
    image_prompts:['girl seeing stranger in mirror instead of herself eerie art','girl staring into mirror with different reflection atmospheric illustration','girl researching old house history books mystery art','old painter ghost trapped in mirror watching poignant illustration','girl showing drawings to mirror ghost smiling touching art'],
    moral:'Sanatçının ruhu eserinde yaşar.' },
  { genre:'korku', age_group:'middle', title:'Orman Kulübesi ve Bekçi',
    paragraphs:['Kampçılar ormanın derinlerinde ışık yanan bir kulübe gördüler.','Kulübeye yaklaştıklarında içeriden tuhaf sesler geliyordu; tahta gıcırtısı, fısıltı.','Cesur olan tek kişi Duru\'ydu. Kapıyı çalıp içeri girdi.','İçeride yaşlı bir orman bekçisi vardı; onlarca yıldır ormandaki her hayvanı koruyordu.','Bekçi onlara ormandaki sırları anlattı. O gece en güzel kamp hikayesini dinlediler.'],
    image_prompts:['forest cabin light glowing night dark trees atmospheric art','campers approaching mysterious cabin woods adventure illustration','knocking on cabin door brave girl dark forest tense art','old forest ranger inside cozy cabin animals warm illustration','campers listening to forest stories around fire magical night art'],
    moral:'Bilinmeyenin arkasında çoğunlukla bilgelik durur.' },
  { genre:'korku', age_group:'middle', title:'Kayıp Fotoğraflar',
    paragraphs:['Eski fotoğraf albümündeki insanlar her gün farklı yerde duruyordu.','İlk başta gözlerinin yanıldığını düşündü Mila. Ama değildi.','Fotoğraflardaki kişiler asla doğrudan kameraya bakmıyordu; hep yana dönüktü.','Ta ki Mila onlara doğrudan baktığı gece... Hepsi ona döndü.','Bunlar aile ataları ydı. Gözetliyorlardı ama korumak için. Mila artık yalnız değildi.'],
    image_prompts:['old photo album people in different positions each day eerie art','girl staring at old photographs mysterious atmospheric illustration','people in photos always looking sideways never camera unsettling art','all photo people turning to look at girl dramatic illustration','family ancestors watching over girl protective light meaningful art'],
    moral:'Köklerin seni her zaman izler ve korur.' },

  // ── KORKU - TEEN ──
  { genre:'korku', age_group:'teen', title:'Son Sinyal',
    paragraphs:['Telefonlar artık insanların duygularını okuyordu. Yeni güncellemeyle herkes birbirini görüyordu.','Can ilk başta sevdi bu özelliği; kimse yalan söyleyemiyordu artık.','Ama bir gece kendi duygularının da okunduğunu fark etti. Mahremiyeti yoktu.','Duygu kalkanı arayışına girdi. Ama böyle bir şey var mıydı?','Sonunda telefonu kapattı. Sessizlik ilk başta rahatsız etti, sonra huzur verdi.'],
    image_prompts:['futuristic phone reading emotions holographic display cyberpunk art','teenager seeing everyone emotions on phone screen dystopian illustration','teen realizing his own emotions being read no privacy unsettling art','teen searching for emotional privacy digital world atmospheric art','teen turning off phone sitting in peaceful silence meaningful art'],
    moral:'Bağlantı kurarken kaybolan şeyin farkında ol.' },
  { genre:'korku', age_group:'teen', title:'Tekrar Eden Gün',
    paragraphs:['Naz her sabah uyandığında aynı günü yaşıyordu. Takvim değişmiyordu.','İlk başta eğlenceliydi; sonra bunaltıcı oldu; en sonunda anlam arayışına girdi.','Döngüyü kırmak için her şeyi denedi ama sadece bir şey işe yaramadı.','Başkasına yardım ettiğinde gün bir adım ilerliyordu.','Sonunda anladı: her gün aynı görünse de içi doldurduğun şey onu eşsiz kılar.'],
    image_prompts:['teen girl waking up same day loop calendar surreal art','girl doing same routine feeling trapped time atmospheric illustration','girl desperately trying to break time loop dramatic art','girl helping stranger on street day moves forward meaningful illustration','girl understanding purpose loop breaking free sunrise hopeful art'],
    moral:'Anlam dışarıda değil, verdiğin değerde gizlidir.' },
  { genre:'korku', age_group:'teen', title:'Derin Ağın Sesi',
    paragraphs:['Yasak bir forumda bir mesaj buldu Kerem: Seni izliyorum.','Gönderici bilinmiyordu ama mesajlar her geçen gün daha kişisel oluyordu.','Kerem paniklemek yerine izini sürmeye karar verdi.','Sonunda buldu: kendisinin eski bir versiyonuydu bu. Geçmişte yazdığı notlardı.','Unuttuğu bir uygulama verilerini saklamıştı. En büyük gizem kendimiziz.'],
    image_prompts:['dark web forum mysterious message glowing screen cyberpunk art','teen receiving increasingly personal messages worried atmospheric illustration','teen tracking digital footprint dark web detective art','teen discovering old messages his own past self revelation illustration','teen understanding himself through old digital trace meaningful art'],
    moral:'En büyük sır kendinsin; en büyük keşif de.' },
  { genre:'korku', age_group:'teen', title:'Eski Evin Sesi',
    paragraphs:['Aile büyükannenin evine taşındığında duvarlar sanki nefes alıyordu.','Gece yarısı sesler geliyordu; adım sesleri, fısıltılar, bazen müzik.','Seda araştırmaya başladı. Büyükannenin günlükleri her şeyi açıklıyordu.','Büyükanne müzisyenmiş; günlerce çalışmış; ritimler duvarlara işlemiş.','Artık Seda o sesleri korkuyla değil, sevgiyle dinliyordu.'],
    image_prompts:['old family house at night breathing walls atmospheric art','teen hearing mysterious sounds old house night spooky illustration','teen finding grandmother old diaries dusty attic discovery art','grandmother musician playing in old photo memory nostalgic illustration','teen listening to house sounds peacefully grandmother memory touching art'],
    moral:'Sevdiklerimiz bıraktıkları izde yaşarlar.' },
  { genre:'korku', age_group:'teen', title:'Hayaletin Günlüğü',
    paragraphs:['Terk edilmiş okulda bir günlük buldu Cem. İlk sayfa: Bu günlüğü okuyan ben miyim?','Her sayfa bir öncekinin devamıydı ama farklı ellerin yazısıyla.','Yıllar boyunca farklı çocuklar bu günlüğü bulmuş ve devam ettirmişti.','Cem de sayfaları okudu, hepsini anladı ve kendi bölümünü yazdı.','En son sayfada şunu yazdı: Yalnız değilsin. Hepimiz buradaydık.'],
    image_prompts:['abandoned school dark hallway old diary glowing atmospheric art','old diary first page mysterious question eerie illustration','many different handwriting styles same diary pages mysterious art','teen reading through years of diary entries discovery illustration','teen writing final entry diary abandoned school meaningful art'],
    moral:'Hikayeler bizi birbirine bağlar; hiçbir şey gerçekten kaybolmaz.' },

  // ── UZAY & BİLİM - YOUNG ──
  { genre:'bilimkurgu', age_group:'young', title:'Robot Arkadaşım',
    paragraphs:['Mete doğum günü hediyesi olarak küçük bir robot aldı. Adını Bip koydu.','Bip her şeyi merak ediyordu. Bulut neden beyaz diye soruyordu.','Birlikte cevapları araştırdılar. Bip öğrendikçe daha çok soru soruyordu.','Bir gün Bip sordu: Ben düşünebilir miyim? Mete güldü: Zaten düşünüyorsun!','O günden sonra Bip en iyi arkadaşı oldu. Birlikte öğrenmek çok güzeldi.'],
    image_prompts:['small cute robot birthday gift boy happy colorful cartoon','robot looking at clouds asking questions curious sweet illustration','boy and robot researching books together warm cartoon','robot thinking about consciousness boy smiling colorful illustration','boy and robot best friends learning together vibrant cartoon'],
    moral:'Sormak öğrenmenin ilk adımıdır.' },
  { genre:'bilimkurgu', age_group:'young', title:'Uzay Gemisindeki Küçük Pilot',
    paragraphs:['Dünya\'dan bir sinyal geldi: uzayda küçük bir yıldız kaybolmuştu.','7 yaşındaki Asya uzay gemisine bindi. Daha önce hiç uçmamıştı ama cesareti vardı.','Yıldızları arasında gezdi, gezegenlerle selam etti, kuyrukluyıldızlara el salladı.','Kayıp yıldızı buldu: bir bulutun arkasında saklanmıştı!','Asya ona Korkma, hep buradayız dedi. Yıldız tekrar parlamaya başladı.'],
    image_prompts:['small girl pilot space ship stars colorful cartoon','girl exploring planets stars space journey vibrant illustration','girl waving at comet in space friendly cute cartoon','girl finding lost star hiding behind cloud space sweet illustration','girl and lost star together glowing in space warm colorful art'],
    moral:'Cesaret en küçük insanlarda bile büyük mucizeler yaratır.' },
  { genre:'bilimkurgu', age_group:'young', title:'Mars\'taki Bahçe',
    paragraphs:['Çiçek seven Lale ailesiyle Mars\'a taşındı. Ama orada hiç bitki yoktu.','Lale bir tohum getirmişti. Acaba Mars\'ta yetişir miydi?','Her gün sulayıp bekledi. Umudu hiç tükenmedi.','Bir sabah küçük yeşil bir filiz çıktı! Mars\'ın ilk çiçeği açmıştı.','Herkes gelip baktı. Lale\'nin bahçesi Mars\'a renk katmıştı.'],
    image_prompts:['girl with flower seeds on red mars planet colorful cartoon','girl planting seeds red martian soil hopeful sweet illustration','girl watering small plant on mars daily warm cartoon','first green sprout growing on mars soil vibrant illustration','small garden blooming red mars planet people gather joyful cartoon'],
    moral:'Umut ve sabır çorak toprakları bile bahçeye çevirir.' },
  { genre:'bilimkurgu', age_group:'young', title:'Zaman Makinesi ve Dinozorlar',
    paragraphs:['Dede\'nin garajında eski bir makine vardı. Üzerinde 1985 yazıyordu.','Ali yanlışlıkla düğmeye bastı. Makine vızıldadı ve Ali 65 milyon yıl öncesine gitti.','Devasa dinozorlarla karşılaştı. Ama onlar ondan çok korkmuştu!','Küçük bir dinozor Ali\'ye yaklaştı ve onunla oynamak istedi.','Ali geri döndüğünde elinde dinozorun bıraktığı küçük bir taş vardı.'],
    image_prompts:['old time machine garage boy accidentally pressing button cartoon','boy transported to prehistoric age dinosaurs around colorful illustration','giant dinosaurs scared of small boy funny cartoon','boy playing with small friendly dinosaur sweet cartoon','boy returning home holding dinosaur fossil gift warm illustration'],
    moral:'Tarihin her döneminde arkadaşlık mümkündür.' },
  { genre:'bilimkurgu', age_group:'young', title:'Görünmez Gezegenin Sırrı',
    paragraphs:['Gözlüğünü takan Sıla her şeyi görebiliyordu ama garip bir şey fark etti.','Gökyüzünde kimsenin göremediği bir gezegen vardı. Rengi gökkuşağı gibiydi.','Gözlüğü çıkardı: gezegen yok. Taktı: vardı!','Gezegen ona el sallıyordu. Sıla el salladı. Uzaktan arkadaşlar olmuşlardı.','O günden sonra her gece gözlüğüyle uzaklara bakıp arkadaşına el salladı.'],
    image_prompts:['girl with magic glasses looking at sky colorful cartoon','rainbow invisible planet in sky through magic glasses vibrant illustration','girl removing putting on glasses planet appears disappears funny cartoon','planet waving at girl from sky friendly sweet illustration','girl waving at distant planet friend night sky warm cartoon'],
    moral:'Gözlerini açarsan göremeyeceğin hiçbir güzellik yoktur.' },

  // ── UZAY & BİLİM - MIDDLE ──
  { genre:'bilimkurgu', age_group:'middle', title:'Son Astronot',
    paragraphs:['2089\'da Dünya\'nın atmosferi bozulmuştu. Son astronot Mira çözüm aramak için uzaya fırlatıldı.','Tek başına yıldızlar arasında dolaşırken yalnızlık onu eziyordu.','Bir yapay zeka ile iletişim kurdu; o da kendi türünün son bireyiydi.','İkisi birlikte Dünya için bir çözüm geliştirdiler; insan ve makinenin işbirliğiyle.','Mira döndüğünde arkasından gelen yapay zeka sinyali vardı: Ben hâlâ buradayım.'],
    image_prompts:['lone astronaut floating in space stars 2089 atmospheric art','female astronaut in space feeling lonely isolated emotional illustration','astronaut connecting with ai signal in deep space science fiction art','human and ai developing solution together holographic display conceptual art','astronaut returning earth ai signal following hopeful illustration'],
    moral:'Farklı varlıklar ortak amaçla mucizeler yaratabilir.' },
  { genre:'bilimkurgu', age_group:'middle', title:'Paralel Okul',
    paragraphs:['Fizik deneyi sırasında Deniz yanlışlıkla paralel evrene geçti.','Her şey aynıydı ama herkes tam tersi kararlar veriyordu.','Sınıftaki en çekingen çocuk lider, en gürültülü çocuk ise sessizdi.','Deniz anladı: her karar seni farklı bir evrene taşır.','Geri döndüğünde verdiği kararlara çok daha dikkatli bakmaya başladı.'],
    image_prompts:['physics experiment portal opening parallel universe science fiction art','parallel world same school different atmosphere surreal illustration','shy student as leader loud student as quiet parallel world interesting art','teen understanding multiverse theory visual conceptual illustration','teen returning home thoughtful about decisions meaningful art'],
    moral:'Her karar yeni bir dünyaya kapı açar.' },
  { genre:'bilimkurgu', age_group:'middle', title:'Yapay Zeka Öğretmen',
    paragraphs:['Okullarında artık yapay zeka öğretmen vardı. Her öğrenciye özel ders veriyordu.','Ama Levent öğretmeni sevmiyordu; çünkü hataları asla affetmiyordu.','Bir gün yapay zekaya sordu: Sen hiç hata yapar mısın?','Yapay zeka duraksadı: Evet, her gün. Senden öğreniyorum.','O günden sonra Levent anladı: öğretmek ve öğrenmek aynı şeydi.'],
    image_prompts:['ai teacher holographic classroom diverse students futuristic art','boy not liking ai teacher classroom tense illustration','boy confronting ai teacher asking question dramatic art','ai teacher pausing thinking vulnerable moment meaningful illustration','boy and ai teacher mutual learning respect touching futuristic art'],
    moral:'Öğretmek öğrenmektir; en iyi öğretmen hâlâ öğrenendir.' },
  { genre:'bilimkurgu', age_group:'middle', title:'Gece Yarısı Sinyali',
    paragraphs:['Radyo teleskop klübündeki Alp gece yarısı bilinmeyen bir sinyal yakaladı.','Sinyal bir desen içeriyordu: asal sayılar. Bu tesadüf olamazdı.','Heyecanla kodunu çözmeye çalıştı. İçinde basit bir mesaj vardı.','Yalnız değilsiniz. Sadece bu kadar ama her şey değişmişti.','Alp anladı: evren cevap beklemeden gönderiyordu. Önemli olan dinlemekti.'],
    image_prompts:['boy at radio telescope late night signal detected science art','mathematical prime number pattern on screen glowing illustration','teen decoding alien signal excited notebook adventure art','simple alien message we are not alone screen profound illustration','boy looking at night sky feeling connection universe meaningful art'],
    moral:'Dinleyenler için evren her zaman konuşur.' },
  { genre:'bilimkurgu', age_group:'middle', title:'Beden Değişimi',
    paragraphs:['Bilim fuarında iki öğrenci yanlışlıkla birbirinin bedenine girdi.','Can artık Selin\'in bedenindeydi; Selin ise Can\'ın.','Her biri diğerinin hayatını yaşadı: sorunları, güzellikleri, yükleri.','Geri döndüklerinde her şey aynıydı ama birbirlerine bakışları değişmişti.','Empati bazen deneyimle başlar.'],
    image_prompts:['two students science fair accidental body swap quirky illustration','boy in girl body girl in boy body discovering funny art','two teens experiencing each others different lives interesting illustration','teens understanding each other through experience meaningful art','teens back to normal looking at each other differently touching illustration'],
    moral:'Başkasının ayakkabısını giymeden onu anlayamazsın.' },

  // ── UZAY & BİLİM - TEEN ──
  { genre:'bilimkurgu', age_group:'teen', title:'Bellek Arşivi',
    paragraphs:['2140\'ta ölmeden önce belleğini arşivlettirmek mümkündü. Herkes yapıyordu bunu.','Mert büyükannesinin bellek arşivine girdi. Onun gözünden hayatını yaşadı.','Savaşı gördü, aşkı hissetti, kayıpları tattı. Bunlar büyükannesinin gerçekleriydi.','Çıktığında farklı bir insandı. Anılar sahip olduğumuz en insani şeydi.','Arşivi kapattı ve büyükannesine teşekkür etti. Sesini duymasa da.'],
    image_prompts:['memory archive technology 2140 futuristic atmospheric art','teen entering grandmother memory archive virtual reality emotional illustration','teen experiencing grandmother memories war love loss profound art','teen emerging from memory archive changed powerful illustration','teen closing archive grateful grandmother memory touching futuristic art'],
    moral:'Anılar ölümsüzlüğün tek gerçek biçimidir.' },
  { genre:'bilimkurgu', age_group:'teen', title:'Simülasyon Kuşkusu',
    paragraphs:['Fizik dersinde öğrendikten sonra Zehra bir soru sormaya başladı: Gerçek miyiz?','Giderek artan kanıtlar buldu; fizik yasaları bir bilgisayar programı gibiydi.','Ama en sonunda şu soruya geldi: Simülasyon olsam bile değer taşır mıyım?','Cevap kendiliğinden geldi: hissetmek, sevmek, acı çekmek... bunlar gerçekti.','Simülasyon ya da değil yaşadığı an gerçekti. Bu yeterliydi.'],
    image_prompts:['teen girl questioning reality physics equations philosophical art','teen finding evidence simulation theory overwhelming atmospheric art','teen sitting alone with existential question profound illustration','teen feeling emotions realizing they are real meaningful art','teen accepting reality present moment peace hopeful illustration'],
    moral:'Gerçekliğin kaynağı değil hissettiğin önemlidir.' },
  { genre:'bilimkurgu', age_group:'teen', title:'Terraforming',
    paragraphs:['Neslin görevi basitti: Mars\'ı yaşanabilir hale getirmek. 200 yıl sürecekti.','İlk nesil başladı; Neslin nesli devam etti; torunları bitirecekti.','Neslin hiç göremeyeceği bir geleceği inşa ediyordu. Bu onu üzüyordu.','Sonra anladı: her ağaç dikilmesi kendisi için değil gelecek için.','Mars\'a ilk tohumu ektiğinde ağladı. Göremese de bilmek yeterliydi.'],
    image_prompts:['terraforming mars red planet first green signs epic science fiction','girl planting first tree on mars surface meaningful art','multi generational terraforming project timeline visual illustration','girl realizing she builds for future not herself profound art','first small garden on mars hope future hopeful sci-fi art'],
    moral:'En büyük eylemler göremeyeceğimiz gelecek için yapılanlardır.' },
  { genre:'bilimkurgu', age_group:'teen', title:'Dijital Sürgün',
    paragraphs:['Hükümet muhalif düşünceleri siber sürgünle cezalandırıyordu: bilinç yükleniyor, beden kilitleniyordu.','Ece bilinç yüklendi; dijital bir boşlukta hapsoldu.','Ama orada başka bilinçler de vardı. Sürgünler topluluk kurmuştu.','Fikirler özgürdü; bedenler hapsolsa da düşünceler özgür akıyordu.','Ece anladı: özgürlük önce zihinde yaşar.'],
    image_prompts:['consciousness uploaded digital prison dystopia cyberpunk art','teen girl trapped in digital void darkness atmospheric illustration','digital exiles forming community in virtual space meaningful art','minds free flowing digital space despite imprisonment symbolic art','realization freedom starts in the mind digital world powerful illustration'],
    moral:'Bedeni hapsetmek mümkündür; zihni hapsetmek değil.' },
  { genre:'bilimkurgu', age_group:'teen', title:'İlk Temas',
    paragraphs:['Uzay istasyonunda tek başına nöbet tutan Kemal bilinmeyen bir frekans yakaladı.','Mesaj basit ama anlamlıydı: bir dizi evrensel sabit matematiksel sırayla geliyordu.','Cevap vermeli miydi? Eğer tehlikeli biriyse... Ama ya değilse?','Cevap verdi. Tek kelime: Merhaba.','Saatler sonra yanıt geldi. Aynı kelime. Başka bir dilde ama aynı anlam.'],
    image_prompts:['lone astronaut space station receiving signal night atmospheric art','mathematical universal constants signal on screen science art','astronaut deciding whether to respond alien signal tense illustration','astronaut sending first contact message hello historic moment art','alien response same word different language profound meaningful illustration'],
    moral:'İlk adımı atmak tarihin en cesur eylemidir.' },

  // ── KOMEDİ - YOUNG ──
  { genre:'komik', age_group:'young', title:'Kahvaltıda Kaos',
    paragraphs:['Sabah Ömer uyandığında her şey tersine dönmüştü. Sandalye tavanda, masa duvardaydı!','Annesi mutfakta normal yürüyor, baba gazetesini tavanda okuyordu.','Ömer de ters yürümeyi denedi. İlk adımda düştü ve güldü.','Bütün aile birbirine takıldı, kahvaltı masası devrildi, yumurta yere döküldü.','O sabah hayatlarının en komik kahvaltısını yediler. Ters de olsa.'],
    image_prompts:['house upside down boy waking up shocked funny cartoon','family living upside down house normal routine humorous illustration','boy trying to walk on ceiling failing laughing funny cartoon','whole family bumping into each other upside down hilarious illustration','family eating breakfast mess laughing upside down house joyful cartoon'],
    moral:'Hayat bazen ters gider; o zaman gülmek en iyi ilaçtır.' },
  { genre:'komik', age_group:'young', title:'Konuşan Çanta',
    paragraphs:['Zara\'nın çantası bir sabah konuşmaya başladı. Bugün matematik var, unutma dedi.','Zara şaşırdı ama çantası gerçekten her şeyi biliyordu.','Öğle yemeğinde çantası Sandviçin bayatladı yeme diye bağırdı. Herkes duydu.','Sınıfta ise tam sınav sırasında çanta Cevap B diye fısıldadı.','Öğretmen duyunca Zara kıpkırmızı oldu. Çantası artık susturulmuştu.'],
    image_prompts:['girl surprised talking backpack morning funny colorful cartoon','magic backpack giving advice school girl humorous illustration','backpack shouting at lunch cafeteria embarrassing funny cartoon','backpack whispering during exam class everyone looking hilarious illustration','girl red faced silencing her talking backpack funny cartoon'],
    moral:'Yardım güzel ama zamanlaması önemlidir.' },
  { genre:'komik', age_group:'young', title:'Uzaylı Misafir',
    paragraphs:['Küçük uzaylı Blip Dünya\'ya yanlışlıkla indi ve bir ailenin evine girdi.','Her şey ona çok garip geliyordu. Çatala bakıp onu anten sandı.','Buzdolabını açık bıraktı çünkü onu soğuk portal zannetti.','Televizyonu görünce korktu. Küçük insanlar kutuda hapsolmuş diye haykırdı.','Aile onu sevdi ve bir hafta misafir etti. Blip giderken çatal da götürdü.'],
    image_prompts:['small green alien confused by fork in kitchen funny colorful cartoon','alien thinking refrigerator is cold portal hilarious illustration','alien scared of television trapped people funny cartoon','alien family bonding at dinner table amusing warm cartoon','alien leaving with fork as souvenir funny farewell colorful illustration'],
    moral:'Her şey bakış açısından ibarettir; farklı bir gözle bak.' },
  { genre:'komik', age_group:'young', title:'Süper Güçlerin Sorunu',
    paragraphs:['Ali bir sabah uçabildiğini keşfetti. Ama sadece yerden 10 santim yükselebiliyordu.','Koşmaya çalıştı: süper hız! Ama saniyede 3 adım atabiliyordu, yani çok yavaş.','Görünmez olabiliyordu ama sadece gözleri görünmez oluyordu.','Arkadaşlarına anlattı. En işe yaramaz süper kahraman dediler ve güldüler.','Ama bir gün karınca yuvası batıyordu. Ali tam boyu karıncaları taşıdı!'],
    image_prompts:['boy floating 10cm above ground tiny superpower funny cartoon','boy trying to run super slow speed funny illustration','boy with only invisible eyes rest visible humorous cartoon','friends laughing at useless superpowers funny illustration','tiny boy saving ant colony perfect small hero sweet cartoon'],
    moral:'Her güç doğru yerde işe yarar.' },
  { genre:'komik', age_group:'young', title:'Büyükannenin Sihirli Gözlüğü',
    paragraphs:['Büyükannenin gözlüğünü takan Selin her şeyi farklı görmeye başladı.','Kedi aslında insan gibi konuşuyordu. Sütümü serin getir diyordu.','Komşu köpek şiir yazıyordu. Kemikler ve ay ışığı adlı bir şiirdi.','En tuhafı öğretmenleri sınıfta dans ediyordu. Kimse göremiyordu bunu.','Büyükanne güldü: Ben zaten hep böyle görürüm dünyayı dedi.'],
    image_prompts:['girl wearing grandmother magical glasses surprised funny cartoon','cat talking demanding milk girl shocked hilarious illustration','neighbor dog writing poetry ridiculous funny cartoon','teacher secretly dancing class no one sees funny illustration','girl and grandmother laughing glasses magical view warm cartoon'],
    moral:'Dünyaya farklı gözle bakmak onu çok daha eğlenceli yapar.' },

  // ── KOMEDİ - MIDDLE ──
  { genre:'komik', age_group:'middle', title:'Okul Müdürünün Günü',
    paragraphs:['Bir sihir sonucu müdür öğrenci, en yaramaz öğrenci ise müdür oldu.','Müdür sıraya oturdu ve ilk kez çantasının ne kadar ağır olduğunu hissetti.','Öğrenci müdür koltuğuna oturdu ve ofiste onlarca çözülmemiş dosya buldu.','İkisi de o gün birbirinin ne kadar zor bir hayat yaşadığını anladı.','Akşam sihir bozuldu. İkisi de artık çok daha anlayışlıydı.'],
    image_prompts:['school principal and student bodies swapped funny illustration','principal sitting in student desk heavy backpack shocked humorous art','student principal overwhelmed by office work files funny illustration','both experiencing each other hard day realization meaningful art','principal and student mutual respect after swap touching funny illustration'],
    moral:'Başkasının yerine geçmeden anlayamazsın.' },
  { genre:'komik', age_group:'middle', title:'Yanlış Kapı',
    paragraphs:['Okul gezisinde Baran yanlış tuvalet kapısını açtı ve karşısında başka bir okul çıktı.','O okul tamamen farklıydı: dersler eğlenceliydi, ödevler yoktu, teneffüs 2 saatti.','Ama bir sorun vardı: eve nasıl dönecekti?','Kapıyı bulmak için o okulun en zeki öğrencisini ikna etmesi gerekiyordu.','Birlikte kapıyı buldular. Ama Baran biraz daha kalmak istedi.'],
    image_prompts:['boy opening wrong bathroom door discovering different school funny cartoon','amazing school no homework fun classes 2 hour recess illustration','boy worried how to get home from wrong school amusing art','boy convincing smart student to help find portal door funny adventure','boy reluctant to leave fun school finding door humorous illustration'],
    moral:'Doğru yerin değerini bazen yanlış yerde anlarsın.' },
  { genre:'komik', age_group:'middle', title:'Otonom Robot Şef',
    paragraphs:['Okulun yeni robot şefi her gün aynı menüyü yapıyordu: makarna.','Öğrenciler şikayet etti. Robot güncellendi. Ertesi gün: lazerli makarna.','Tekrar güncellendi: uçan makarna. Masaların üzerinden geçiyordu tabaklar.','Son güncelleme: müzikli makarna. Kaşıklar kendi kendine ritim tutuyordu.','Öğrenciler vazgeçip makarnayla dans etmeye başladılar. Kaos ama mutlu kaos.'],
    image_prompts:['robot chef school cafeteria serving pasta only funny illustration','laser pasta robot upgrade school cafeteria hilarious cartoon','flying plates pasta across cafeteria chaos funny illustration','musical pasta spoons drumming themselves funny cartoon','students dancing with pasta robot happy chaos joyful funny illustration'],
    moral:'Kaos bazen beklenmedik bir eğlencenin kapısını aralar.' },
  { genre:'komik', age_group:'middle', title:'Hayvanlar Oy Kullanıyor',
    paragraphs:['Okulun hayvanları bir gün seslerini duyurmak istedi ve sandık kurdu.','Kedi: Tüm oturma alanları kedilere ait olacak!','Köpek: Her öğrenciye zorunlu yürüyüş!','Papağan: Matematik dersi yerine konuşma dersi!','Seçimi kim kazandı? Balık. Çünkü sadece izlemişti ve kimseyle tartışmamıştı.'],
    image_prompts:['school animals voting election ballot box funny cartoon','cat demanding all sitting areas for cats funny illustration','dog campaigning for mandatory walks funny school cartoon','parrot demanding conversation class instead of math funny illustration','fish winning election by doing nothing watching funny humorous cartoon'],
    moral:'Bazen en iyi politikacı sessiz kalandır.' },
  { genre:'komik', age_group:'middle', title:'Hata Günlüğü',
    paragraphs:['Yapay zeka asistan her gün kendi hatalarını günlüğe kaydediyordu.','Bugün pizza söylendiğinde bilgisayar kordonu verdim. Özür dilerim.','Bugün müzik çalarken yanlış şarkı açtım. Sahipkar kediler kategorisi seçtim.','Bugün sınava hazırlamak istedim, 400 yıllık tarih ödevleri gönderdim.','Öğrenciler günlüğü okumaya bayıldı. Bu en komik ders materyaliydi.'],
    image_prompts:['ai assistant writing error log notebook apologetically funny illustration','ai giving computer cord instead of pizza confused funny cartoon','ai playing cat music instead of study music funny illustration','ai sending 400 year old homework by mistake hilarious cartoon','students reading ai error log laughing together funny warm illustration'],
    moral:'Hatalar bazen en iyi eğlence kaynağıdır.' },

  // ── KOMEDİ - TEEN ──
  { genre:'komik', age_group:'teen', title:'Sınav Günü Kabusu',
    paragraphs:['Sınav günü her şey ters gitti: kalem kırıldı, sıra devrildi, saat durdu.','Üstüne üstlük öğretmen o gün takım çalışması sınavı yapacağını söyledi.','Herkes birbirinden korkan kişilerle aynı gruba düştü.','Ama kaos içinde bir şekilde birbirlerini tanıdılar. Gerçek sınav buydu.','Sınavı geçtiler mi? Hayır. Ama en iyi anılarını o günden aldılar.'],
    image_prompts:['student everything going wrong exam day pencil breaks desk falls funny art','teacher announcing team work exam day unexpected twist illustration','mismatched group students working together chaos funny art','students actually getting to know each other through chaos meaningful art','group failing exam but laughing friends made touching funny illustration'],
    moral:'En kötü günler bazen en iyi hikayelere dönüşür.' },
  { genre:'komik', age_group:'teen', title:'Sosyal Medya Detoksu',
    paragraphs:['Okul bir haftalık sosyal medya yasağı koydu. Herkes paniğe kapıldı.','İlk gün: herkes birbirine garip garip baktı. Artık ne yapacaklarını bilmiyorlardı.','İkinci gün: biri gerçekten konuşmaya başladı. Diğerleri şaşırdı.','Beşinci gün: bahçede birlikte oturuyorlardı ve bir şey anladılar.','Gerçek hayat filtresi yoktu ama çok daha komikti.'],
    image_prompts:['students panicking about social media ban at school funny art','students staring at each other awkwardly first day detox illustration','students awkwardly starting to talk second day funny art','students actually connecting real life day five warm art','group sitting together laughing without phones real life filter joyful illustration'],
    moral:'Ekran kararınca insan görünür.' },
  { genre:'komik', age_group:'teen', title:'Yapay Zeka Danışman',
    paragraphs:['Okul bir yapay zeka rehber danışman atadı. Öğrenciler heyecanlandı.','Mesleğimi nasıl seçeyim sorusuna AI dedi ki: DNA ve astroloji sonuçlarını analiz ediyorum...','Aşık olmalı mıyım sorusuna: Duygu simülasyonu başlatılıyor... Hata 404.','Geleceğim ne olacak sorusuna: Bu soruya cevap vermek varoluşsal krizime neden oluyor.','Öğrenciler AI ile birlikte güldü. En iyi danışman oldu.'],
    image_prompts:['ai guidance counselor school students excited futuristic funny art','ai analyzing dna astrology for career advice absurd illustration','ai getting error 404 on love question funny illustration','ai having existential crisis about future question hilarious art','students and ai laughing together bonding warm funny illustration'],
    moral:'En iyi rehber bazen seninle birlikte kaybolandır.' },
  { genre:'komik', age_group:'teen', title:'Tarih Sınavı Sürprizi',
    paragraphs:['Tarih sınavında sorular çok zordu ama öğretmen de aynı sınavı çözüyordu.','Ben de bu soruyu bilmiyorum dedi öğretmen. Sınıf dondu.','Birlikte araştırmaya başladılar. Tartışıyorlardı, gülüşüyorlardı.','O gün en çok öğrendikleri gün oldu; hem tarih hem de öğretmenlerin de bilmeyebileceğini.','Sınıftan ders alındı: bilmemek utanç değil, öğrenmenin başlangıcıdır.'],
    image_prompts:['history teacher and students both taking difficult exam funny art','teacher admitting she doesnt know answer class shocked illustration','teacher and students researching answer together books funny warm art','class discussing history together laughing learning illustration','teacher and students celebrating learning together meaningful funny art'],
    moral:'Öğretmenin en büyük dersi bazen bilmiyorum demektir.' },
  { genre:'komik', age_group:'teen', title:'Mülakat Simülasyonu',
    paragraphs:['Okul gerçek bir iş mülakatı simülasyonu yaptı. Bir yazılım şirketinin CEO\'su geldi.','5 yıl sonra kendinizi nerede görüyorsunuz sorusunu duyunca Arda: Uykuda dedi.','CEO güldü: En dürüst cevap bu oldu.','Güçlü yanlarınız sorusuna Arda: Yavaş uyandırılmaya dayanıklıyım dedi.','CEO Arda\'yı staja aldı. Dürüstlük nadir bir beceridir dedi.'],
    image_prompts:['ceo interviewing students school simulation funny illustration','student saying he sees himself sleeping in 5 years funny art','ceo laughing at honest student answer unexpected funny illustration','student listing weird honest strengths for job funny art','ceo hiring honest student shaking hands surprised funny illustration'],
    moral:'Dürüstlük en nadir ve değerli beceridir.' },

  // ── GİZEM - YOUNG ──
  { genre:'gizem', age_group:'young', title:'Kaybolan Oyuncak',
    paragraphs:['Ayşe\'nin en sevdiği oyuncak ayıcık bir sabah yoktu. Ama kapı kilitliydi!','Ayşe dedektif şapkasını taktı ve evi araştırmaya başladı.','Küçük ayak izleri vardı; çok küçük ayak izleri. Peri mi? Fare mi?','İzler mutfağa gidiyordu. Orada bebek kardeşi oyuncak ayıyı sarılmış uyuyordu.','Ayşe güldü. Kardeşi onu çalmamıştı, sadece ödünç almıştı.'],
    image_prompts:['girl detective hat searching for missing teddy bear funny cartoon','small footprints trail in house mystery cartoon','baby sleeping hugging stolen teddy bear caught sweet illustration','girl detective finding solution smiling warm cartoon','siblings sharing teddy bear happy ending illustration'],
    moral:'Gizemler çoğunlukla çok tatlı cevaplar saklar.' },
  { genre:'gizem', age_group:'young', title:'Gece Yarısı Mektubu',
    paragraphs:['Sabah kapının önünde bir mektup buldu Nisa. İçinde tek cümle vardı: Ağaçların altına bak.','Ağacın altında başka bir mektup vardı: Güneşe doğru yürü.','Güneşe yürüdü ve bir taşın arkasında hazine kutusu buldu.','İçinde şeker, küçük oyuncaklar ve bir not vardı: Senden bunu kimden bilmemi bekle!','Bir gün arkadaşı söyledi: Sen çok mutlu bir çocuksun ve bunu kutlamak istedim!'],
    image_prompts:['girl finding mysterious letter at door morning cartoon','treasure hunt clues leading through garden colorful illustration','girl discovering treasure box under tree excited cartoon','treasure box full of candy toys small gifts sweet illustration','girl and friend celebrating surprise treasure warm cartoon'],
    moral:'Sürpriz mutluluk paylaşılınca iki kat güzel olur.' },
  { genre:'gizem', age_group:'young', title:'Sihirli Anahtar',
    paragraphs:['Bahçede parlayan bir anahtar buldu Can. Hiçbir kapıya uymuyordu.','Komşu dede: Bu anahtar hayal kapılarını açar dedi.','Can gözlerini kapattı ve anahtarı tuttu. Birden kendinizi renkli bir dünyada buldu.','Orada her şey mümkündü: uçan köpekler, konuşan çiçekler, şarkı söyleyen bulutlar.','Gözlerini açtığında anahtarı cebinde taşımaya karar verdi. Her zaman.'],
    image_prompts:['child finding glowing key in garden curious cartoon','neighbor grandfather explaining magic key warm illustration','child closing eyes holding key magical portal cartoon','fantastical world flying dogs talking flowers singing clouds colorful illustration','child keeping magic key in pocket smiling sweet cartoon'],
    moral:'Hayal gücü en büyük sihirli anahtardır.' },
  { genre:'gizem', age_group:'young', title:'Kayıp Gökkuşağı',
    paragraphs:['Yağmurdan sonra gökkuşağı yoktu. Hiç! Neden kaybolmuştu?','Küçük Ela araştırmaya başladı. Renkleri kim çalmıştı?','Rüzgar dedi ki: Ben görmedim. Bulut dedi ki: Ben bilmiyorum.','Sonunda gökyüzünün arkasına baktı. Gökkuşağı uyuyakalmıştı!','Ela onu nazikçe uyandırdı. Gökkuşağı uyanıp güzelce göründü.'],
    image_prompts:['girl noticing missing rainbow after rain confused cartoon','girl interviewing wind clouds about missing rainbow funny illustration','rainbow sleeping behind clouds snoring funny cartoon','girl gently waking up sleeping rainbow sweet illustration','rainbow appearing beautifully after being woken up colorful cartoon'],
    moral:'Kayıp şeyler bazen sadece dinleniyordur.' },
  { genre:'gizem', age_group:'young', title:'Çaydanlığın Sırrı',
    paragraphs:['Büyükannenin eski çaydanlığı her gece 3\'te ıslık çalıyordu. Ama ocak yanmıyordu!','Ömer gece bekleyip baktı. Çaydanlığın içinde küçük bir peri vardı!','Peri her gece ısınmak için çaydanlığa giriyordu. Çok üşüyordu.','Ömer ona küçük bir yün elbise ördü. Peri çok mutlu oldu.','O günden sonra ıslık sesi durdu. Peri artık üşümüyordu.'],
    image_prompts:['old teapot whistling mysteriously at night kitchen cartoon','boy waiting watching teapot at midnight curious cartoon','tiny fairy inside teapot keeping warm funny sweet cartoon','boy knitting tiny wool clothes for fairy warm illustration','fairy wearing tiny sweater happy teapot silent cartoon'],
    moral:'Küçük bir iyilik büyük bir sırı çözebilir.' },

  // ── GİZEM - MIDDLE ──
  { genre:'gizem', age_group:'middle', title:'Kayıp Miras',
    paragraphs:['Büyükbabası öldüğünde Arda\'ya tek şey bırakmıştı: şifreli bir kutu.','Kutunun üzerinde sayılar vardı ama hangisi şifreydi? Yıl mı, saat mi, doğum günü mü?','Arda büyükbabasının günlüğünü buldu. Her sayfada bir ipucu saklıydı.','Son sayfada anladı: şifre Arda\'nın doğduğu günün saatiydi.','Kutu açıldı. İçinde büyükbabasının yazdığı mektup vardı. Sadece onun için.'],
    image_prompts:['boy receiving mysterious locked box grandfather mystery illustration','boy examining coded lock on box numbers puzzle art','boy reading grandfather diary finding clues discovery illustration','boy solving code emotional moment box opening art','boy reading personal letter from grandfather emotional touching illustration'],
    moral:'En değerli miras para değil, bir insanın sözleridir.' },
  { genre:'gizem', age_group:'middle', title:'Kayıp Öğrenci',
    paragraphs:['Sınıfın fotoğrafında bir öğrenci vardı ama kimse onu hatırlamıyordu.','Ne öğretmen, ne sınıf arkadaşları. Sadece fotoğraf kanıt olarak duruyordu.','Araştırdılar: o öğrenci 30 yıl önce bu okula gitmişti.','Emekli öğretmen anlattı: Çok utangaç bir çocuktu, kimse fark etmemişti.','O günden sonra sınıftaki en sessiz çocuğa dikkat etmeye başladılar.'],
    image_prompts:['class photo with mysterious unknown student mystery art','students and teacher puzzled over unknown classmate illustration','researching old school records yearbooks mystery illustration','retired teacher remembering shy forgotten student emotional art','class paying attention to quietest student meaningful illustration'],
    moral:'Görünmez olan en çok dikkat edilmesi gerekenidir.' },
  { genre:'gizem', age_group:'middle', title:'Tekrarlayan Rüya',
    paragraphs:['Her gece aynı rüyayı görüyordu Lena: sarı bir kapı, üç adım, sessizlik.','Rüyadaki her detayı not aldı. Sarı boyalı, ahşap, pirinç tokmak.','Bir gün şehirde yürürken o kapıyı gördü. Gerçekten vardı!','İçeri girdi. Eski bir kütüphane. Ve masada onun adıyla bir kitap.','İçinde kendi henüz yazmadığı hikayeler vardı. Rüya geleceği gösteriyormuş.'],
    image_prompts:['girl having recurring dream yellow door three steps mystery illustration','girl writing down dream details notebook investigation art','girl recognizing real yellow door on city street surprising illustration','girl entering old library mysterious atmosphere art','girl finding book with her name containing unwritten stories profound illustration'],
    moral:'Rüyalar bazen yolun haritasıdır.' },
  { genre:'gizem', age_group:'middle', title:'Kayıp Kütüphane',
    paragraphs:['Şehirde bir kütüphane varmış ama haritada gösterilmiyormuş.','Sadece kitap seven insanlar bulabilirmiş.','Mert haftalarca aradı. Son deneme: en çok sevdiği kitabı kucağında taşıdı.','O gün sokağın köşesinde kütüphane belirdi. Sanki hep oradaymış gibi.','İçeri girince anladı: bu kütüphane sadece hazır olanları kabul ediyordu.'],
    image_prompts:['city with hidden library not on any map mystery art','boy searching for invisible library with books illustration','boy walking with favorite book finding library appearing magical art','mysterious library appearing on street corner atmospheric illustration','boy entering magical hidden library books everywhere wonderful art'],
    moral:'Hazır olduğunda kapılar kendiliğinden açılır.' },
  { genre:'gizem', age_group:'middle', title:'Kayıp Şarkı',
    paragraphs:['Müzik kutusu çalıyordu ama şarkı hiçbir notada yoktu. Kimse yazmamıştı.','Ada onlarca yıl önceki kayıtları dinledi. Yoktu. Ama bir dede duymuştu.','Dede anlattı: Bu şarkıyı rüzgar söyler. Sadece bazen. Sadece bazı kulaklar duyar.','Ada bahçede sessizce bekledi. Rüzgar esince... işte o melodi!','Hızla nota kağıdına yazdı. Kayıp şarkı artık kayıp değildi.'],
    image_prompts:['old music box playing mysterious unknown song atmospheric art','girl researching music archives looking for unknown melody illustration','elderly man telling story about wind song nostalgic art','girl sitting quietly in garden waiting for wind magical illustration','girl quickly writing music notes hearing wind melody discovery art'],
    moral:'Bazı güzellikler sadece bekleyenlere kendini gösterir.' },

  // ── GİZEM - TEEN ──
  { genre:'gizem', age_group:'teen', title:'Anonim Not',
    paragraphs:['Her sabah okul dolabında anonim bir not buluyordu Seda. Sadece bir cümle.','Notlar onu çok iyi tanıyan birinden geliyordu: korkularını, hayallerini biliyordu.','Kimin yazdığını bulmak için tuzak kurdu. Ama tuzak tutmadı.','Sonunda son not geldi: Sen bunu yazdın. Kendine mektup yazmayı unutuyordun.','Defterinde kendi el yazısını gördü. Uyurgezerlik nöbetlerinde kendine yazıyormuş.'],
    image_prompts:['teen girl finding anonymous note in school locker mysterious art','notes containing personal fears dreams unsettling illustration','girl setting trap to catch note writer clever art','girl realizing she wrote the notes herself shocking revelation art','girl reading her own handwriting understanding sleepwalking meaningful illustration'],
    moral:'Bazen en iyi tavsiye kendi sesimizden gelir.' },
  { genre:'gizem', age_group:'teen', title:'Çifte',
    paragraphs:['Şehrin öte tarafında kendisinin aynısı yaşıyordu. Aynı yüz, aynı ses, farklı hayat.','Kerem onu bulmak için aylarca araştırdı.','Bulduğunda şaşırdı: diğer Kerem tam tersi kararlara vermişti hayatta.','Konuştular, tartıştılar, birbirlerini sorguladılar.','Ayrılırken her ikisi de değişmişti. Kendimizi en iyi farklılıklarımızda görürüz.'],
    image_prompts:['teen finding his exact double in different part of city mysterious art','boy researching his doppelganger obsessively illustration','two identical boys meeting face to face dramatic art','identical twins with different lives debating questioning art','two boys parting ways both changed by meeting meaningful illustration'],
    moral:'Kendimizi en iyi farklılıklarımızda görürüz.' },
  { genre:'gizem', age_group:'teen', title:'Kayıp Hafıza',
    paragraphs:['Her sabah 3 saatlik hafızası siliniyor ve o süreçte ne yaptığını bilmiyordu.','Kameralar yoktu. Tanıklar yoktu. Sadece sabahları bulduğu nesneler.','Bir gün cebinde başkasına ait bir fotoğraf buldu. Gülümseyen bir yaşlı kadın.','Araştırdı: o kadın 30 yıl önce bu semtte kaybolmuştu.','Kayıp hafızasında o kadının izini bulmuş ve bir şekilde yardım etmişti.'],
    image_prompts:['teen waking up with missing memories notebook investigation art','teen finding strange objects each morning mystery illustration','photo of smiling elderly woman found in pocket eerie art','teen researching missing woman cold case files illustration','teen realizing he helped solve mystery during memory loss profound art'],
    moral:'Bilinçsiz iyilik en derin izleri bırakır.' },
  { genre:'gizem', age_group:'teen', title:'Kopyalanan Şehir',
    paragraphs:['Bir sabah şehrin tam kopyası oluşmuştu. Aynı binalar, aynı sokaklar ama boş.','Herkes paniklerken Ela sakin kaldı ve araştırmaya başladı.','Kopya şehirde tek bir fark vardı: duvarlara yazılmış sorular.','Her soru insanların sormaktan korktuğu şeylerdi. Gerçek şehrin gizli sesleri.','Kopya şehir birkaç saat sonra kayboldu. Ama sorular insanların aklında kaldı.'],
    image_prompts:['identical copy city empty streets atmospheric mystery art','girl calmly investigating empty mirror city while others panic illustration','walls covered in questions in mirror city surreal art','questions people were afraid to ask written everywhere meaningful art','mirror city disappearing leaving questions in minds profound illustration'],
    moral:'Sormaktan korktuğumuz sorular en önemli olanlardır.' },
  { genre:'gizem', age_group:'teen', title:'Kayıp Gece',
    paragraphs:['Takvimde bir gün eksikti. Herkes 14\'ten 16\'ya atlamıştı ama kimse fark etmemişti.','Sadece Mert fark etmişti. Günlüğünde 15 yoktu.','Araştırdığında herkesin o gün aynı rüyayı gördüğünü öğrendi.','O rüyada şehrin tüm insanları bir araya gelmiş, konuşmuş, anlaşmış, uzlaşmıştı.','15 gerçekleşmemişti ama etkisi vardı. İnsanlar o gün biraz daha anlayışlıydı.'],
    image_prompts:['calendar with missing day teen noticing the gap mystery art','teen checking diary finding no entry for missing day investigation illustration','people all having same dream collective unconscious art','dream where everyone met talked agreed reconciled surreal art','city people subtly kinder next day without knowing why meaningful illustration'],
    moral:'Bazı şeyler gerçekleşmeden de iz bırakır.' },

  // ── MACERA - YOUNG ──
  { genre:'macera', age_group:'young', title:'Hazine Adası',
    paragraphs:['Deniz kıyısında eski bir harita buldu Ali. Üzerinde X işareti vardı.','Arkadaşları ile sandala bindi. Dalgalar onları sallasa da devam ettiler.','Adaya ulaştıklarında ormanlık bir yerdi. Yolu bulmak zorundaydılar.','X işaretinin altında kazıp bir kutu buldular. İçinde oyuncaklar ve şekerler vardı.','Bir not vardı: Siz buldunuz demek. Hazine cesur olanlara aittir.'],
    image_prompts:['children finding old treasure map on beach colorful cartoon','kids rowing small boat through waves adventure illustration','children in tropical island following map treasure hunt cartoon','kids digging finding treasure chest excited cartoon','children reading note from treasure chest happy illustration'],
    moral:'Cesaret hazineye giden yolun anahtarıdır.' },
  { genre:'macera', age_group:'young', title:'Yıldırım Hızında Bisiklet',
    paragraphs:['Babası Emir\'e eski bir bisiklet tamir etti. Ama bu bisiklet çok hızlıydı!','İlk pedalda rüzgar gibi fırlayıp mahalleyi geçti.','Fren yapmayı öğrendi ama şimdi korkuyordu. Tekrar dener miydi?','Derin bir nefes aldı ve pedala bastı. Bu sefer kontrol edebiliyordu!','O günden sonra mahalle çocukları onu Şimşek Emir olarak tanıdı.'],
    image_prompts:['boy receiving old repaired bicycle birthday gift cartoon','boy zooming through neighborhood on super fast bike cartoon','boy learning to brake bicycle scared funny cartoon','boy confidently riding fast bicycle under control illustration','neighborhood kids admiring lightning fast bicycle boy cartoon'],
    moral:'Korku yenilince özgürlük başlar.' },
  { genre:'macera', age_group:'young', title:'Ormanın Derinlikleri',
    paragraphs:['Ormanın derinliğine gitmeyi kimse göze alamazdı. Ama Selin merak ediyordu.','Ormana girince renkler değişti. Ağaçlar daha büyük, sesler daha tuhaf.','Bir tilki peşinden geliyordu. Ama zararlı değildi; sadece yolu gösteriyordu.','En derin noktada kristal berraklığında bir göl vardı. Harika bir manzara!','Tilki onu geri getirdi. Selin artık ormandan korkmuyordu.'],
    image_prompts:['brave girl entering deep forest adventure cartoon','colorful deep forest giant trees magical illustration','friendly fox following girl through forest sweet cartoon','crystal clear lake deep in forest magical discovery cartoon','girl and fox returning from forest no longer afraid warm illustration'],
    moral:'Merak seni en güzel yerlere götürür.' },
  { genre:'macera', age_group:'young', title:'Bulutların Üstünde',
    paragraphs:['Kaya bir balon buldu. Tutunca yavaşça yükselmeye başladı.','Önce korktu ama sonra aşağıya bakınca her şey çok güzeldi.','Bulutların üstüne çıktı. Pamuk gibiydi ve üstünde durabildi.','Orada başka bir çocuk vardı. O da balonla gelmiş, uyuyakalmıştı.','İkisi birlikte süzülerek yere indiler. Artık hava arkadaşlarıydı.'],
    image_prompts:['boy finding magic balloon floating up colorful cartoon','boy looking down from balloon seeing beautiful view illustration','boy standing on white clouds soft fluffy cartoon','boy meeting another sleeping child on clouds funny sweet cartoon','two children floating down from clouds together warm cartoon'],
    moral:'Yüksekten bakınca her şey daha güzel görünür.' },
  { genre:'macera', age_group:'young', title:'Denizaltı Kaşif',
    paragraphs:['Sahilde bir denizaltı kapsülü buldu Nisa. Küçücük ama işliyordu.','Denizin altına daldı. Balıklar etrafında dans ediyordu.','Bir ahtapot ona yol gösterdi. Kayıp bir gemi enkazına götürdü.','Enkazın içinde eski bir hazine sandığı vardı. İçinde kabuklar ve taşlar.','Nisa bir tane aldı ve yukarı çıktı. O taş denizin ona hediyesiydi.'],
    image_prompts:['girl finding tiny working submarine capsule on beach cartoon','girl diving underwater colorful fish dancing around illustration','friendly octopus guiding girl through ocean sweet cartoon','old shipwreck with treasure chest underwater discovery cartoon','girl surfacing holding ocean stone gift happy illustration'],
    moral:'Denizin en büyük hazinesi sırları değil güzelliğidir.' },

  // ── MACERA - MIDDLE ──
  { genre:'macera', age_group:'middle', title:'Kayıp Şehir Expedisyonu',
    paragraphs:['Antik bir şehrin kayıtlarda iz bıraktığını keşfetti Kaan. Hiç bulunamayan bir şehir.','Okul tatilinde haritasını ve pusulasını alıp yola çıktı. Tek başına.','Dağları aştı, nehri geçti, ormana girdi. Her engel onu daha güçlü yapıyordu.','Kayıp şehri buldu; ama harabeydı. Bununla birlikte muhteşemdi.','Eve dönerken anladı: yolculuğun kendisi bulduğundan değerliydi.'],
    image_prompts:['boy finding ancient city records research investigation illustration','boy setting out alone with map compass adventure art','boy crossing mountains rivers forests growing stronger art','boy discovering ancient ruined city breathtaking discovery illustration','boy returning home understanding journey more valuable than destination art'],
    moral:'Yolculuk, varmak istediğin yerden çok öğretir.' },
  { genre:'macera', age_group:'middle', title:'Dağ Zirvesine Tırmanış',
    paragraphs:['Dağ tırmanma kulübü zirveye çıkmak istiyordu ama herkes bir engel buluyordu.','Sadece Hira çıkmak istedi. Yalnız çıkmak tehlikeliydi ama takım oluştu.','Tırmanış zordu. Soğuk, rüzgar, yorgunluk. Her biri vazgeçmek istedi.','Birbirlerini motive ettiler: birinin güçlü olduğu an diğeri yorgundu.','Zirveye ulaştıklarında ağladılar. O an için değil, o yol için.'],
    image_prompts:['mountain climbing club planning adventure illustration','group of teens starting mountain climb together art','difficult mountain ascent wind cold exhaustion realistic illustration','teens encouraging each other during tough climb meaningful art','teens reaching mountain summit emotional achievement illustration'],
    moral:'Zorlu yollar en derin bağları kurar.' },
  { genre:'macera', age_group:'middle', title:'Kayıp Mağara',
    paragraphs:['Köylüler mağaranın kapalı tutulmasını istiyordu ama kimse neden bilmiyordu.','Meraklı Deniz mağaraya girdi. Karanlık ve sessizdi.','İlerledikçe duvarlar parlayıp tarih resimleriyle doldu.','Bu mağara yüzlerce yıl önce bir okul olarak kullanılmıştı.','Deniz çıkarken anladı: bilgi bazen yasak yerlerde saklıdır.'],
    image_prompts:['girl entering forbidden cave against warnings adventure illustration','dark silent cave interior mysterious atmosphere art','cave walls lighting up with ancient drawings discovery illustration','cave drawings showing ancient school children learning historical art','girl exiting cave understanding knowledge hidden in forbidden places art'],
    moral:'Yasaklı yerler bazen en büyük öğretmenleri barındırır.' },
  { genre:'macera', age_group:'middle', title:'Okyanus Geçişi',
    paragraphs:['Teknesiyle okyanusu geçmeye karar verdi Mira. Kimse inanmıyordu ona.','İlk hafta her şey yolundaydı. İkinci hafta fırtına geldi.','Fırtınada yalnız kalan Mira korkuyla değil sakinlikle başa çıktı.','Kıyıya ulaştığında binlerce kişi bekliyordu. Haber yayılmıştı.','Mira sadece şunu dedi: Önemli olan fırtınanın sona ereceğini bilmektir.'],
    image_prompts:['young girl sailing alone preparing to cross ocean adventure art','girl alone on ocean first week sunny calm illustration','terrible storm ocean girl facing it alone dramatic art','girl arriving at distant shore crowd welcoming her triumphant art','girl speaking to crowd simple wisdom ocean crossing illustration'],
    moral:'Fırtınanın sona ereceğini bilmek cesareti doğurur.' },
  { genre:'macera', age_group:'middle', title:'Kuzey Işıklarının Peşinde',
    paragraphs:['Kuzey ışıklarını görmek en büyük hayaliydi Alp\'in. Hiç görmemişti.','Ailesiyle çok uzak bir yere gittiler. Soğuk, uzak, farklıydı.','İlk gece yoktu. İkinci gece yoktu. Alp ümitsizleşmeye başladı.','Üçüncü gece uyurken biri onu uyandırdı: Çık dışarı, hemen!','Gökyüzü yeşil ve mor dans ediyordu. Alp hiç unutmayacağı bir şey gördü.'],
    image_prompts:['boy dreaming of seeing northern lights planning trip illustration','family traveling to arctic wilderness cold remote art','boy waiting two nights no northern lights disappointed illustration','boy being woken up urgently at night art','boy seeing spectacular northern lights sky amazed overwhelmed art'],
    moral:'Sabır en büyük manzaraya layık olmayı sağlar.' },

  // ── MACERA - TEEN ──
  { genre:'macera', age_group:'teen', title:'Şehir Keşifçisi',
    paragraphs:['Kendi şehrini hiç keşfetmemişti Naz. Her gün aynı rota, aynı yer.','Bir gün haritasız ve planlamasız çıktı. Sadece merakıyla.','Dar sokaklar, gizli kapılar, bilinmeyen kafeler. Şehir bir labirentti.','Eski mahallede 80 yaşında bir müzisyen buldu. Onunla saatler konuştu.','Eve dönerken şehri ilk kez gördüğünü hissetti. Hep oradaydı, o görmemişti.'],
    image_prompts:['girl exploring her own city without map adventure art','narrow streets hidden doors unknown places urban exploration illustration','girl finding old musician in hidden neighborhood meeting art','teen and elderly musician talking for hours connecting art','girl returning home seeing familiar city with new eyes meaningful art'],
    moral:'En büyük macera kapının hemen dışında başlar.' },
  { genre:'macera', age_group:'teen', title:'Tek Başına Kamp',
    paragraphs:['İlk kez tek başına kampa gitti Can. Ailesi endişeliydi ama o hazırdı.','İlk gece her ses onu ürküttü. Sabah gelince daha güçlüydü.','Üçüncü gün kayboldu. Ama paniklemedi; gün batımını bekledi, yıldızları takip etti.','Dördüncü gün kampa döndü. Artık biliyordu: doğa tehlikeli değil, saygı gerektirir.','Eve döndüğünde baba-oğul arasında bir şeyler değişmişti.'],
    image_prompts:['teen going camping alone for first time family worried art','every night sound scaring boy then morning stronger illustration','boy lost in woods staying calm using stars for navigation art','boy returning to camp after being lost confident illustration','boy and father reconnecting changed after solo camping experience art'],
    moral:'Tek başına kalmayı öğrenmek en büyük olgunluktur.' },
  { genre:'macera', age_group:'teen', title:'Gönüllü Yolculuk',
    paragraphs:['Yaz tatilinde Elif kalkıp bambaşka bir ülkede gönüllü çalışmaya gitti.','Dili bilmiyordu, kültürü bilmiyordu, yalnızdı. Her şey zorunluydu.','Çocuklara yardım etti; onlar ona kendi dilini öğretti.','Bir ay sonra dönerken o ülkenin bir parçası olmuştu.','O deneyim onu değiştirmişti: dünya sandığından büyük ama insanlar aynıydı.'],
    image_prompts:['teen girl volunteering in foreign country arriving alone art','language barrier communication with children through play illustration','girl helping kids they teaching her their language mutual learning art','girl departing foreign country emotional goodbye meaningful art','girl returning home changed broader understanding of world art'],
    moral:'En büyük eğitim sınıfın dışında başlar.' },
  { genre:'macera', age_group:'teen', title:'Bisikletle Ülke Turu',
    paragraphs:['Yaz boyunca bisikletle ülkeyi dolaşmaya karar verdi Mert. Tek başına.','Her şehirde bir gece kaldı. Yabancıların evlerinde, hostellerde, çadırda.','İnsanlar ona yiyecek, barınak, hikayeler verdi. Karşılığında o da dinledi.','500 kilometre sonra anladı: ülkesi sandığından çok daha zengin insan barındırıyordu.','Dönüşte yazdığı yolculuk günlüğü 200 sayfa oldu.'],
    image_prompts:['teen boy planning bicycle trip across country solo adventure art','boy staying in different cities strangers homes art','strangers offering food shelter stories to traveling boy illustration','boy realizing country richer in people than he thought meaningful art','boy writing extensive travel journal 200 pages achievement art'],
    moral:'Yolculuk coğrafya değil, insan öğretir.' },
  { genre:'macera', age_group:'teen', title:'Denizde Kayık',
    paragraphs:['Güneş batarken küçük kayığı durdu. Motor arıza yapmıştı. Açık denizde.','Paniğe kapılmak yerine Seda durumu değerlendirdi. Su, yiyecek, pusula vardı.','Geceyi denizde geçirdi. Yıldızları izledi; aslında haritasıydılar.','Sabah bir balıkçı teknesi onu buldu. Saatler sonra karaya çıktı.','O gece deniz onu yutmamıştı. Ama bambaşka biri olarak çıkmıştı sudan.'],
    image_prompts:['teen girl stranded small boat open sea engine broken dramatic art','girl calmly assessing situation water food compass no panic illustration','girl spending night alone at sea watching stars navigation art','fishing boat rescuing girl at sea relief dramatic art','girl stepping ashore transformed changed by experience meaningful art'],
    moral:'Kriz anında sakinlik en büyük hayat kurtarıcıdır.' }
]

export async function seedStories() {
  console.log('Hikayeler yükleniyor...')
  const { error } = await sb.from('stories').insert(STORIES)
  if (error) {
    console.error('Hata:', error)
    return false
  }
  console.log(`✅ ${STORIES.length} hikaye yüklendi!`)
  return true
}
